### ISSUE TITLE
Remap JMP Config

### ISSUE THREAD

**Issue by dedenbangkit** [akvo/rtmis#402]
- Option Codes: [option_list.xlsx](https://github.com/akvo/rtmis/blob/develop/doc/surveys/option_list.xlsx)
- Option Map: https://docs.google.com/spreadsheets/d/1nTU6V_vy8IzOsA_EUrG6YNHBCGNchGa7/edit#gid=957279647

**Comment by abhishek-p-s** [comment]
@joycarpediem @dedenbangkit in the above excell ( given in the https://github.com/akvo/rtmis/issues/402 issue) some of the variable name and some questions are missed, which i have given as null array for now. we can see some of the graph not loading this is because of the values dosen't exist. below i have added the missing item from the excell


WASH in Schools

Drinking water -> Basic -> S_water_source (S-1, S-2, S-3, S-4 or S-5)
Drinking water -> Limited -> S_water_source (S-1, S-2, S-3, S-4 or S-5) S_water_available (S-1)
Drinking water -> No service -> S_water_source (S-6, S-7 or S-8)

Sanitation -> Basic -> ss_toilet_type (SS-1,SS-2 or SS-3) and ss_girls_only (SS-1) and ss_latrine_use (SS-1)
Sanitation -> Basic -> ss_toilet_type (SS-1,SS-2 or SS-3) and ss_girls_only (SS-1) and ss_latrine_use (SS-1)
