### ISSUE TITLE
Remove/disable delete button for manage data for all user roles except county admin and super admin for approved data

### ISSUE THREAD

**Issue by joycarpediem** [akvo/rtmis#635]

**Comment by dedenbangkit** [comment]
@kevinmugambi what do you mean ANY Levels? who's going to delete the data if all the answers is wrong?

**Comment by kevinmugambi** [comment]
For Kenya government systems, we don't delete data or users at any level. For data, we only provide options to recall and edit the data because of periodic retrospective analysis. For users, we only provide option to deactivate but not delete. Deletion of users happens in exceptional cases like death. If you have to delete, you must provide option to re-assign historical data.

**Comment by dedenbangkit** [comment]
Yes, currently we don't delete the users, we actually deactivate them, we just need to
- [ ] rename the button to deactivate
- [ ] **show inactive user** tick beside **show pending user** (to include inactive users to the list)
- [ ] api to recall the user

**Comment by joycarpediem** [comment]
@dedenbangkit , please do now work on this issue till i ask you to do so
